### PR TITLE
[TA-11022] Update country list

### PR DESCRIPTION
**Pull request by kizza**
Specifically intended to match commandcentre's recent country naming update https://github.com/everydayhero/command_centre/commit/ea0d439e933b7bf4ff42d1dbcac91137e0daefb7 which pulls all in step.

The intention is to apply this as a patch release to the current 3.7.0 (ie. if the labels are newer, go with them)

### CODE REVIEW

**Comment by bradparker** [comment]
Technically this is a breaking change rather then a minor one. So semver is more or less off the table :)

**Comment by kizza** [comment]
@bradparker - yeah that was my thinking (darn it).   So i'm confused as to the best release version then - what would you go for?

**Comment by kizza** [comment]
If it was just country labels it would be fine... I wonder if that's a better approach to go for "for now", which then just makes it a patch?

**Comment by bradparker** [comment]
If the label change has it broken now, then I guess there's not much we can do? 
I'd go for what ever makes it easier to release.
This is going into command centre?

**Comment by kizza** [comment]
This pr does not address the issue of the `UK` key in widgets vs the `GB` key in commandcentre (it doesn't seem to matter)

**Comment by bradparker** [comment]
Cool, looks less drastic? I do hate the fact that we deal interchangeably with country names and iso codes.

**Pull request merged**
