### PR TITLE
TA 7481 UI updates to address widget

### PR DESCRIPTION
**Pull request by bradparker**
screen shot 2015-09-22 at 2 56 11 pm

screen shot 2015-09-22 at 2 56 30 pm

screen shot 2015-09-22 at 2 56 48 pm

screen shot 2015-09-22 at 2 57 06 pm

### CODE REVIEW

**Comment by davidherse** [comment]
Need to increment version number

**Comment by davidherse** [comment]
Also, I feel like we might need a rule or something to make the "Can't see your address? Enter manually." look more clickable.

**Comment by bradparker** [comment]
@davidherse no worries cheers

**Comment by bradparker** [comment]
screen shot 2015-09-24 at 2 53 22 pm

Kinda sorta?

**Comment by bradparker** [comment]
screen shot 2015-09-24 at 2 57 17 pm

With less craaaazy spacing.

**Pull request merged**
